### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by maplewang** [idevz/vanilla#101]
is there any instructions? I want to debug at local windows.
Thanks

**Comment by idevz** [comment]
@maplewang sorry for a long time no reply, and sorry too for no instructions for windows, but you still can deploy vanilla manually in your Window.

*set up framework*

```bash
./configure --prefix=$VANILLA_FRAMEWORK_ROOT --openresty-path=$OPENRESTY_ROOT
make install
```

*set up your first vanilla app*

```bash
$VANILLA_BIN new $VANILLA_APP_ROOT
#you can find $VANILLA_BIN in your $VANILLA_FRAMEWORK_ROOT/bin path
#$VANILLA_APP_ROOT is the full path where you want to put your app.
```
