### ISSUE TITLE
What is the usage (how to use), files under /vanilla/sys/nginx/*.lua

### ISSUE THREAD

**Issue by aguereca** [idevz/vanilla#105]
I can see good pieces of code there but I don't see where is it used, is that deprecated. If so, is there a reason for it?

**Comment by idevz** [comment]
@aguereca very sorry about the later reply, those code is for the old vanilla(before V0.1.0-rc4.0) , used to generation the nginx.conf automatic, but now we use `/vanilla/sys/application.lua` to instead.
