### ISSUE TITLE
how to start my own app after install vanilla?

### ISSUE THREAD

**Issue by yanglo** [idevz/vanilla#2]
after I intalled vanilla, i still have no idea about how to start my own app with vanilla, i think i would take me too much time to learn how to start vanilla. so I hope it could support a simple demo or a quick start page to help us to start my own app with vanilla faster...

**Comment by idevz** [comment]
Hi @yanglo !
First, you could run a command like `vanilla new app_demo` to start a simple app named app_demo, and `cd app_demo` run `vanilla start` to start your own app, And you can find more detail about how to use vanilla in README.md, or [Docs-zh](https://idevz.gitbooks.io/vanilla-zh/content/)， [Docs-en](https://idevz.gitbooks.io/vanilla-doc/content/)
