### ISSUE TITLE
Docker start failed

### ISSUE THREAD

**Issue by shoother** [idevz/vanilla#21]
> vanilla start vdemo

显示出错信息：

> ERROR: Cannot initialize launcher: /usr/local/share/lua/5.1/vanilla/v/libs/utils.lua:54: attempt to index local 'f' (a nil value)

**Comment by idevz** [comment]
@shoother 
`vanilla start/stop/restart/reload`命令需要在项目路径下运行
cd进vdemo目录。然后vanilla start
