### ISSUE TITLE
默认application接收到请求是怎么找到view和controller的?

### ISSUE THREAD

**Issue by xiangjie256329** [idevz/vanilla#25]
接收到请求:http://127.0.0.1:9110/
1:根据配置跳转
/vanilla/test/tmp/development-nginx.conf:
    location / {
            content_by_lua_file ./pub/index.lua;
    }
2:读取application配置并初始化bootstrap及dispatcher
/vanilla/test/pub/index.lua:  
local config = require('config.application')    //保存controllers和view的路径
local app = require('vanilla.v.application'):new(config)
3:启动
/vanilla/test/pub/index.lua:
app:bootstrap():run()
3.1:执行boostrap(),执行实例中的boot_list()
3.2:执行dispatcher(),执行plugin,初始化controller,view后返回

查根据返回的页面是返回的view和controllers数据集合,但这两个路径在源码中是怎么找到的呢?
/vanilla/test/application/views/index/index.html
/vanilla/test/application/controllers/index.lua

**Comment by idevz** [comment]
@xiangjie256329 你好！
在preDispatch阶段，dispatcher开始根据路由得到的matched_controller和action执行相关的操作：

```
local c_rs = self:lpcall(call_controller, self, matched_controller, self.request.controller_name, self.request.action_name)
```

并将返回结果组装到response中，进行请求响应：

```
self.response.body = c_rs
```
