### ISSUE TITLE
关于开发模式下的log写入。

### ISSUE THREAD

**Issue by shengnoah** [idevz/vanilla#3]
【前提条件】
1.依照github上的readme方式安装vanilla。
2.用非root用户启动vanilla。
3.使用的是development开发模式，端口 7200。

【再现步骤】
1.vanilla start [--trace]
2.tail -f ./logs/development-access.log
3.http://www.openresty.com.cn:7200/index.php
4.http://www.openresty.com.cn:7200/test_waf.php
5.vanilla stop [--trace]

【期待结果】
启动服务后，tail -f development-access.log，伴随每次http请求
实时的输出到访问日志文件里。便于调试监控。

【实际结果】

access log的实时访问数据，只有在vanilla stop [--trace]
之后，才写入到development-access.log。

（PS:某些情况下，会直接抛出写文件异常，error.log,另外一个问题，
忘记截取log了。）

**Comment by idevz** [comment]
@shengnoah 好，我默认的nginx.conf配置里面的access.log配置后面加了个buffer，日志得大于那个值才会写磁盘，你可以改下。
`combined buffer=16k`

```
        # Access log with buffer, or disable it completetely if unneeded
        access_log logs/{{VA_ENV}}-access.log combined buffer=16k;
        # access_log off;
```

另外你说写文件异常是写log吗？是不是权限的问题，你能否给下你的日志。非常感谢。
