### ISSUE TITLE
对restful api编程中参数合法性校验，vanilla有什么打算？

### ISSUE THREAD

**Issue by caidollar** [idevz/vanilla#35]
restful api编程中，需要对post, get过来的参数进行合法性校验，这是一个很繁琐，且重复的代码过程。vanilla有没有打算做比较好的封装？
比如：数据为nil, empty, 是否某个类型，是否符合正则表达式等等。

**Comment by idevz** [comment]
这种类似filter的功能，我们可以考虑加进去，这个比较通用，有兴趣也欢迎你提交PR：）
