### ISSUE TITLE
生产模式下获取不到restful里面的参数

### ISSUE THREAD

**Issue by mind029** [idevz/vanilla#37]
vanilla 生产模式下 在控制器中 使用 self.params['typedir'] 获取 restful 里面的参数，重启 vanilla 第一次访问页面是可以获取得到 ，第二次访问页面就成了nil 

但是在 开发模式下 一直都是能改获取得到的

restful.lua ：
restful.v.GET = {
    {pattern = '/:typedir/:id', controller = 'index', action = 'detail'},
    {pattern = '/:typedir', controller = 'index', action = 'list'},
    {pattern = '/', controller = 'index', action = 'index'},
}

**Comment by idevz** [comment]
@mind029 非常感谢，这是一个restful route的bug，我已经修复，你可以直接更新

```
vanilla/v/routes/restful.lua
```

的代码即可，
非常感谢。
