### ISSUE TITLE
关于vanilla执行顺序

### ISSUE THREAD

**Issue by mind029** [idevz/vanilla#38]
openresty 的 执行顺序：
 set_by_lua
rewrite_by_lua
access_by_lua
content_by_lua
header_filter_by_lua
body_filter_by_lua
log_by_lua

对应vanilla框架 ：
 application（应用代码主体目录）
│   ├── nginx（*Openresty所封装Nginx请求处理各Phase）

在application 下 的nginx文件 该如何对应实现上述 流程呢？

**Comment by idevz** [comment]
@mind029 你好，这个流程的实现是Vanilla起初非常引以为豪的设计，因为Vanilla的初衷就是对OpenResty最大程度的封装，使用者只需要关注自己的业务逻辑，不需要关系OpenResty、Nginx的配置等。所以Vanilla实现了很多OpenResty的指令，包括你列举的这些phase，但是有次在同春哥聊起这个话题的时候，春哥并不建议我们将一个业务细分到各个phase中去，因为每个phase的初始化，API调用环境准备等是需要消耗资源的，Vanilla处理的Web业务完全放到content这个phase就ok。至少应该尽量的将业务集中在某几个phase，而不是各个切分。Vanilla已经提供了插件机制来解决请求阶段处理的问题。
另外回答你的问题，这些phase如何对应于Vanilla。
你看到demo application的nginx目录下面有几个实例文件，以init_by_lua为例，可以将init的lua逻辑实现在这里，实现一个对象，提供一个执行的入口，`run` 方法，例如：

```
local init_by_lua = {}
function init_by_lua:run()
    local conf = require 'nginx.init.config'
    ngx.zhou = conf
end

return init_by_lua
```

这样就定义好了你的init逻辑；
第二步你就可以在项目根目录下面的config/nginx.lua文件中将你的init逻辑配置到 `ngx_conf.common` 段，例如：

```
ngx_conf.common = {
    INIT_BY_LUA = 'nginx.init',
}
```

最后一步，你只需要将  `{{INIT_BY_LUA}}`  配置到config/nginx.conf文件中，重启服务即可。
