### ISSUE TITLE
template 是不是要搞的和jsp asp 什么的一样才是好呢

### ISSUE THREAD

**Issue by cuiweixie** [idevz/vanilla#4]
template 既然是用别人的，不忍直视

**Comment by idevz** [comment]
@cuiweixie 你好，Vanilla的文档里面专门有[一章](https://idevz.gitbooks.io/vanilla-zh/content/sundry/3rd_party_pkg.html)说明Vanilla使用了哪些优秀的第三方库，因为目前只有我一个人开发、运营，时间短，精力有限，一方面为了更快的做起来，更重要的也是为了保证Vanilla的高可扩展性，所以使用了一些库，视图引擎是可插拔的，只要你实现了`display,render,assign,init,new`等这些方法，就可以在bootstrap的时候换成自己的视图引擎。
其实保证扩展性也是考虑到众口难调，Vanilla的做法就是能让用户在不喜欢当前组件的时候可以方便的插拔上自己的组件，另外也非常欢迎你提供更好用的组件，我们一起把Vanilla做的更完善好用。期待你的PR：）
