### ISSUE TITLE
vanilla开发遇到的问题系列------静态资源加载需要注意的地方

### ISSUE THREAD

**Issue by leon1509** [idevz/vanilla#5]
受影响的版本：v0.1.0-rc3

想要在0.1.0-rc3版本中的页面上能正常加载css文件，并且css样式能正常显示，注意要在“你的项目目录/config/nginx.conf”中http部分加入一句：include $openresty/nginx/conf/mime.types;
PS：据说0.1.0-rc4中会解决此问题

**Comment by idevz** [comment]
默认server不提供静态文件服务，所以没有添加mime.types，看来还是有必要添加的 :+1:

**Comment by hcaihao** [comment]
必须要添加！
