### ISSUE TITLE
vanilla关于lua_code_cache使用

### ISSUE THREAD

**Issue by inspire7c** [idevz/vanilla#50]
vanilla在生产环境下开启lua_code_cache后，第一次请求接口输出正常，再次刷新接口后参数就捕获不到了

**Comment by idevz** [comment]
@inspire7c 你好，能否贴出你接口controller的代码一起看下？我们也在用，没发现这样的问题。

**Comment by inspire7c** [comment]
#37 和此问题是一个问题，之前没有仔细看关闭的issues，已经按您的回复找到问题所在，感谢ing!

**Comment by idevz** [comment]
:)
