### ISSUE TITLE
attempt to set ngx.status after sending out response headers

### ISSUE THREAD

**Issue by inspire7c** [idevz/vanilla#51]
log错误日志中，总会记录这么一条记录attempt to set ngx.status after sending out response headers，使用restful路由，直接在controller控制器只是做个输出操作也会记录这么一条日志，是出在配置上吗

**Comment by idevz** [comment]
@inspire7c 请确保你是使用vanilla.v.response处理的业务逻辑，并且在请求响应之前没有ngx.say，print_r等操作。
