### ISSUE TITLE
能否2个路由同时其作用呢

### ISSUE THREAD

**Issue by mind029** [idevz/vanilla#52]
@idevz 京老大，又要麻烦你了，

Bootstrap 路由的 代码：
   local router = self.dispatcher:getRouter()
    local restful_route = require('vanilla.v.routes.restful'):new(self.dispatcher:getRequest())
    router:addRoute(restful_route)      --此时协议栈中加上默认的vanilla.v.routes.simple，一共两个路由协议，如果只想使用一个路由协议，可以给addRoute传入第二个参数true   

vanilla 使用restful路由后，router:addRoute(restful_route) ，没有加true，但是 只有简单路由生效，
必须要加上 true，变成 router:addRoute(restful_route,true) 
restful路由才生效
这2个路由只能有一个起作用 ，能否同时生效呢?
您的注释上写上的： 2个是能起作用的。这个是否是一个bug呢？

**Comment by idevz** [comment]
@mind029 第二个参数设置为true是强制将路由协议栈清空，并加入当前协议。路由协议栈默认就有简单路由协议，多种协议协作完成路由功能（匹配出当前请求应该由哪个controller和哪个action处理），路由的过程是通过遍历协议栈直到得出结果为止。
`router:addRoute(restful_route)`，没有加true，此时路由协议栈加上默认的简单路由协议，就有两种，简单路由先匹配到结果，则直接接受路有过程。

**Comment by mind029** [comment]
实际情况并不是 遍历所有协议栈，直到找到 。不加，只会匹配到 简单路由，然后就不往后面找了。
有时间你可以试一下。

**Comment by idevz** [comment]
@mind029 简单路由就匹配到结果了，当然就直接返回了，为什么还要往下找？还是说不符合简单路由的规则，而是符合restful路由的规则，却只运行了简单路由然后就报无法匹配了？

**Comment by mind029** [comment]
是第二种，符合restful路由规则，，却只运行了简单路由然后就报无法匹配了。
如：router:addRoute(restful_route)，没有加true，
此时：访问一个restful 路由地址，会报错，报错说  匹配不到 路由。module 'controllers.xxx' not found

**Comment by idevz** [comment]
@mind029 你把你的`Bootstrap:initRoute()` 和 `config/restful.lua` 贴出来看看吧

**Comment by mind029** [comment]
这是restful.lua的代码
`local restful = {
    v={}                --web版本定义
}

--路由优先级越在前面匹配度越高
restful.v.GET = {
    {pattern = '/houtai/index', controller = 'admin.index', action = 'index'},--后台管理首页
    {pattern = '/houtai/login', controller = 'admin.index', action = 'login'},--后台登录页面
    {pattern = '/houtai/logout', controller = 'admin.index', action = 'logout'},--后台登录注销
    {pattern = '/spider', controller = 'index', action = 'spider'},
    {pattern = '/tech/:dir/', controller = 'index', action = 'tech'},
    {pattern = '/singer/:id', controller = 'index', action = 'singer'},
    {pattern = '/:typedir/:id', controller = 'index', action = 'detail'},
    {pattern = '/:typedir/', controller = 'index', action = 'list'},
    {pattern = '/shouye', controller = 'index', action = 'new_index'},
    {pattern = '/', controller = 'index', action = 'index'},
}

restful.v.POST= {
    {pattern = '/houtai/login_sub', controller = 'admin.index', action = 'login_sub'},--后台登录提交
}

return restful`

这是Bootstrap:initRoute()的代码

`function Bootstrap:initRoute()
    local router = self.dispatcher:getRouter()
    local restful_route = require('vanilla.v.routes.restful'):new(self.dispatcher:getRequest())
    router:addRoute(restful_route)
end`

这里举例，restful 的 /houtai/login 
访问restful 的 url：http://114.215.93.85:9110/houtai/login   提示控制器找不到，报错，虽然定义了。
访问简单路由的url：http://114.215.93.85:9110/admin/index/login ，能够匹配的到

所以不是2个同时起作用的

**Comment by idevz** [comment]
@mind029 非常感谢，确实是一个路由器的bug，当没有加参数true的时候，restful路由处于路由协议栈的低端，会在simple路由协议之后执行，而simple路由协议总是能返回一个controller和action，路由器里面没有对返回的controller和action是否存在做出判断，仅判断了simple路由协议是否解析正常，我已经新建[分支](https://github.com/idevz/vanilla/tree/vanilla-0.1.0.rc4)修复了这个bug， 你只需要把你的`vanilla.v.router`替换成[https://github.com/idevz/vanilla/blob/vanilla-0.1.0.rc4/vanilla/v/router.lua](https://github.com/idevz/vanilla/blob/vanilla-0.1.0.rc4/vanilla/v/router.lua)即可，有问题随时沟通：）

**Comment by mind029** [comment]
已经正常了。
