### ISSUE TITLE
关于vanilla 插件 的建议

### ISSUE THREAD

**Issue by mind029** [idevz/vanilla#59]
京老大，有个对vanilla插件优化的建议，你看看是否合理：
1、能否为 plugins 里面的插件 绑定到某个 控制器呢？ 因为现在定义的插件，在Bootstrap起码启用是全局的，比如权限检查，只对有些控制器使用，有些不使用。

**Comment by idevz** [comment]
@mind029 插件绑定控制器这个想法很好，感谢你的建议，我回头看看性价比如何，因为如果要绑定则需要在dispatcher里面去添加一些判断和规则，目前这种鉴权如果在路由结束后，根据路由的结果在某些controller里面去做鉴权其实也还好，只有需要的controller才会运行鉴权的逻辑。
