### ISSUE TITLE
vanilla开发遇到的问题系列------页面无法正常显示

### ISSUE THREAD

**Issue by leon1509** [idevz/vanilla#6]
受影响的版本：v0.1.0-rc3

在“你的应用目录/applications/plugins/admin.lua”文件中，将以下部分注释掉，否则你的页面死活可能显示不正常。

routerStartup方法里的：
--print_r('<pre>')
    --if request.method == 'GET' then
    --    print_r('-----------' .. sprint_r(request.headers) .. '----------')
    --else
    --    print_r(request.headers)
    --end

PS：作者在下版本应该会去掉！

**Comment by idevz** [comment]
demo中这部分代码，当初是为了提醒大家vanilla提供了很方便的插件功能，看来不一定必须了 :+1:
