### ISSUE TITLE
Global function defined in bootstrap.lua cannot be called under production mode.

### ISSUE THREAD

**Issue by hcaihao** [idevz/vanilla#63]
I defined some funcs in bootstrap.lua, which to be called in controllers, bu got "attempt to call global 'func_name' ( a nil value)" error. But there is no error under development mode or move those funcs to controllers. I think it was caused by LUA_CODE_CACHE option, If I close the cache, it passed again.

**Comment by idevz** [comment]
you can define your global functions in init_by_lua_\* phase
