### ISSUE TITLE
vanilla开发技巧系列------如何转到非默认视图

### ISSUE THREAD

**Issue by leon1509** [idevz/vanilla#7]
在Controller中，默认是转到views/控制器名称/方法.html，具体写法如下：

function IndexController:index()
    local view = self:getView()
    local p = {}
    p['vanilla'] = 'Welcome To Vanilla...'
    p['zhoujing'] = 'Power by Openresty'
    view:assign(p)
    return view:display()
end

然而有时我们可能会有转到非默认的页面，比如上面的方法想转到/test/help.html，写法如下：

function IndexController:index()
    local view = self:getView()
    local p = {}
    p['vanilla'] = 'Welcome To Vanilla...'
    p['zhoujing'] = 'Power by Openresty'
    return view:render("test/help.html", p)   -- PS：参数p可以省略
end

**Comment by idevz** [comment]
参数p为需要assign的参数
