### ISSUE TITLE
lua_code_cache in conf invalid

### ISSUE THREAD

**Issue by hcaihao** [idevz/vanilla#83]
I switch lua_code_cache to off in nginx_conf/dev_vhost/xxx.conf, then "restart dev". But no change when I refresh the page in browser if I modify code in "application/controllers/index.lua". I means the cache is always on!

Version: rc6 release.

**Comment by idevz** [comment]
I'm so sorry about this late reply, you needn't to switch lua_code_cache but to run `./$VANILLA_APP_ROOT/va-appname-service initconf dev` to init a dev conf.

**Comment by hcaihao** [comment]
It doesn't work! It's a bug.

My step for test this:

```
./setup-framework -v /usr/local/openresty/nginx/lua -o /usr/local/openresty
./setup-vanilal-demoapp -a /usr/local/openresty/nginx/lua/hello -u root -g root -e dev

cd /usr/local/openresty/nginx/lua/hello
./va-hello-service confinit dev
./va-hello-service start dev
```

Then I modify "controllers/index.lua", nothing changed when I refresh page!

**Comment by hongcai** [comment]
try to mute the `page_cache` in file pub/index.lua (line2) @hcaihao
