### ISSUE TITLE
error: attempt to set ngx.status after sending out response headers

### ISSUE THREAD

**Issue by hcaihao** [idevz/vanilla#84]
I need call B controller method "test" from A controller, so I use "ngx.location.capture" in A controller method.

```
function AController:index()
    local res = ngx.location.capture("/B/test")
    return res.body
end
```

```
function BController:test()
    return ""
end
```

I access url "http://host/A" but got "attempt to set ngx.status after sending out response headers" error in "logs/production-error.log", how to fix?

Version: rc4 release.

**Comment by tanxiaolong** [comment]
open "openresty/vanilla/framework/0_1_0_rc6/vanilla/v/dispatcher.lua"
find function : errResponse
comment ngx.eof() then give a try

**Comment by tanxiaolong** [comment]
grep -rn "ngx.eof" ../openresty/vanilla/
change ngx.eof() to ngx.exit() then give a try

**Comment by idevz** [comment]
sorry please use the new version of vanilla
