### ISSUE TITLE
./configure error

### ISSUE THREAD

**Issue by ghost** [idevz/vanilla#85]
When I am running the ./configure error .... i am getting output

Didn't set luajit or lua bin. Or did't exists:/usr/local/openresty/luajit/bin/luajit\* at ./configure line 131.

I have installed libluabind and luarocks lua5.1 ... but still am getting this error ...

Any help ?

**Comment by idevz** [comment]
Hi, you can use the 'setup-framework' script to install vanilla like this: `$ ./setup-framework -v $VANILLA_PROJ_ROOT -o $OPENRESTY_ROOT`.
