### ISSUE TITLE
restful路由模式能否实现html后缀

### ISSUE THREAD

**Issue by mind029** [idevz/vanilla#86]
@idevz 你好，现在发现restful.lua的配置无法实现html后缀的方式访问。
能够实现 http://www.xx.com/xxx/1231.html 这样html后缀呢。router.lua 要怎么改呢？

**Comment by idevz** [comment]
不需要改啊，你直接在 `config/restful.lua` 里面配置就行了。

```
restful.v.GET = {
    {pattern = '/1231.html', controller = 'index', action = 'get'},
}
```

这样就会直接路由到 index controller 的 get action 上面去
