### ISSUE TITLE
lua_code_cache关闭后报500错误

### ISSUE THREAD

**Issue by luduoxin** [idevz/vanilla#87]
修改配置文件lua_code_cache on;为lua_code_cache off;后，重启项目访问报500错误，版本为vanilla-0.1.0.rc6

**Comment by idevz** [comment]
``` bash
./$VANILLA_APP_ROOT/va-appname-service start
```

start 服务前需要先 initconf， 默认是生产环境，也就是 `lua_code_cache on`， `initconf dev` 加 dev 参数后会初始化开发环境的配置，不需要你手动修改配置文件。

**Comment by luduoxin** [comment]
lua_code_cache关闭为什么报500错误？生产环境做限制了吗？

**Comment by idevz** [comment]
如果 start 时没有指定是开发环境，默认会走 `init_worker_by_lua_file`， 此时如果将 lua_code_cache 关闭，会导致由 `init_worker_by_lua_file` 初始化的数据失效，就会报500。
vanilla 中 `lua_code_cache` 不需要手动改变，只需要在运行时指定不一样的启动环境就行。开发环境用 `va-{{APP_NAME}}-service dev`，生产环境用`va-{{APP_NAME}}-service`。
