### ISSUE TITLE
vanilla开发技巧系列------输出json到浏览器

### ISSUE THREAD

**Issue by leon1509** [idevz/vanilla#9]
local cjson = require "cjson"
function IndexController:index()
    -- 解析request参数
    local req = self:getRequest()
    --    print_r(req:getParams())
    local ret = {}
    ret.id = req:getParam("id")
    ret.name = req:getParam("name")
    return cjson.encode(ret)
end

**Comment by idevz** [comment]
thanks :+1:

**Comment by likeog** [comment]
nice.
