### ISSUE TITLE
vanilla /opt/openresty/luajit/bin/luajit: /opt/vanilla/bin/vanilla:2: unexpected symbol near '-'

### ISSUE THREAD

**Issue by Calmds** [idevz/vanilla#90]
![image](https://cloud.githubusercontent.com/assets/11456183/20960276/9d74bea4-bc9a-11e6-9b73-d98056415fed.png)

**Comment by Calmds** [comment]
Version :  vanilla-0.1.0-rc4.1
openresty-version:  openresty-1.11.2.2
the configure cmd: ./configure --prefix=/opt/vanilla --openresty-path=/opt/openresty --with-luajit-or-lua-bin=/opt/openresty/luajit/bin --vanilla-bin-path=/opt/vanilla/bin
OS : Mac os X 10.10.5

**Comment by Calmds** [comment]
the **bin/vanilla** 
![image](https://cloud.githubusercontent.com/assets/11456183/20960427/55870ac4-bc9b-11e6-92c6-90e88c46e7e0.png)

**Comment by idevz** [comment]
@bobleeli may be you should try new version of Vanilla.  `vanilla-0.1.0-rc4.1` is to old to use.
