### ISSUE TITLE
关于 simple 和 restful 的路由选择

### ISSUE THREAD

**Issue by tanxiaolong** [idevz/vanilla#91]
为什么在 router.lua 里指定的是 simple 路由
然后在 app 的 bootstrap 里又换成 restful ？

我意思是确定一种不可以吗？
现在我的项目偶尔会“找不到路由”的错误，我追了一下代码发现是 simple 路由引起的，按理说都应该是 restful 才对吧。能不能统一一下？？都改成 restful ？ @周晶

**Comment by idevz** [comment]
@tanxiaolong `router.lua` 里面指定了默认的路由协议是 `vanilla.v.routes.simple`，如果你需要使用其他的路由协议就需要在 `bootstrap` 中 `initRoute` 里面进行设置。
如下代码：
```lua
    local restful_route = restful:new(self.dispatcher:getRequest())
    router:addRoute(restful_route)
```
就是往路由协议栈中添加了另外一个路由协议 `restful`，此时协议栈中有两个路由协议，都会生效。
如果你只希望使用一个，只需要 `addRoute` 方法的第二个参数设置为 `true` 就行。

**Comment by tanxiaolong** [comment]
@idevz 我找到了代码里“路由找不到”的原因，因为 request header 里 的accept 是一个 table 导致的，正常应该是 string 类型。似乎源码里可以对这种非法类型的情况做一个判断，追代码 debug 了好久。。好辛苦。。
我的解决方法是 在nginx.conf 里配置了一下 `more_set_inpu_headers  "accept *\/*";` 来重新把 req 的 accept 写一次。

**Comment by idevz** [comment]
@tanxiaolong 没明白你的意思，Vanilla 里面 request 获取 header 中的 accept 底层调用的是 `ngx.req.get_headers()`，restful 的路由协议就是这么实现的，路由本身是没问题的啊，你现在的问题是只使用一种路由的情况还是两种同时？框架本身不需要依赖 `headers-more-nginx-module` 模块。

**Comment by tanxiaolong** [comment]
@idevz 不不不，现在不说 restful 和 simple 了，这个搞清楚了。  

正常来讲 accept 的值应该是一个 “string” 类型，但是我当时遇到一个异常，追了好久代码发现 request 的 header 里的 accept 的值居然是一个 “table” 类型，这个异常的 accept 格式是类似这样的：“accept : [*/*,xxx,xxx,xxx]”。  
于是我用 more_set_input_headers 修改了 request header 里的 accept 才使得代码正常运作。
我意思是说或许框架里可以对这种细节做一个判断，不然我（用户）还得在框架之外（比如 more_set_input_headers ）来消除这样的异常。

再一个，现在很蛋疼的一个使用经历就是，遇到 set ngx.status before response 之类 或者 ngx.header before response 的错误总得从框架里一点一点的打 ngx.log 进行 debug。。。
不知您有无啥好的 tip 呢？？？蟹蟹！
