### ISSUE TITLE
解决vanilla多项目使用 resty-template模板缓存问题

### ISSUE THREAD

**Issue by mind029** [idevz/vanilla#92]
vanilla创建项目  web1 和 web2 。2个项目。然后分别修改这个项目项目的模板页面 

**web1项目**的模板 首页模板， web1\application\views\index\index.html
改成：

```
<!DOCTYPE html>
<html>
<body>
<h1>web1</h1>
</body>
</html>
```

**web2项目** 的模板 首页模板， web2\application\views\index\index.html
改成：

```
<!DOCTYPE html>
<html>
<body>
<h1>web2</h1>
</body>
</html>
```

然后随便一个项目 **使用 生产模式 启动**，./va-web1-service start 。

然后访问 先后 web1 和 web2 绑定域名 。**会发现 页面 都为 web1**

这是  resty-template 的缓存问题。现象为 哪个项目先 访问。模板即为那个项目的。

**解决办法**，修改 /vanilla/framework/0_1_0_rc6/vanilla/v/views/rtpl.lua 文件

在template引用地方关闭模板缓存。增加

```
template.caching(false)

```

改成如下：
```--dep
-- https://github.com/bungle/lua-resty-template
local template = require "resty.template"
template.caching(false)
-- perf
local error = error
local pairs = pairs
local setmetatable = setmetatable
local app_root = Registry['APP_NAME']
```

**Comment by idevz** [comment]
@mind029 当模板名相同的时候，确实会有这个问题，resty-template 默认没有对多 APP 做支持，但是你上面的修改方式相当于关闭了 template cache，这样会使每次请求，模板都需要重新编译，可能会有性能问题，我已经修复了这个问题，在 Vanilla 引用的 resty-template 中对 template cache-key 加入了 APP_NAME 来对多 APP 作支持，你可以更新到最新版 Vanilla 试试：）
