### ISSUE TITLE
最新版 vanilla页面缓存 key 设置不合理。

### ISSUE THREAD

**Issue by mind029** [idevz/vanilla#95]
git clone vanilla 最新版本安装。然后创建新项目。切换到 安装 框架的 路径 /opt/vanilla/framework/init.lua

编辑 init.lua 文件：

大概在 195行，找到 页面 设置缓存的唯一 key 。
```
Registry['APP_PAGE_CACHE_KEY'] = ngx.encode_args(clean_args(Registry['REQ_ARGS_ARR']))

```
可以看出 由 参数组成。但是当 页面没任何参数的时候 。APP_PAGE_CACHE_KEY  打印看到为  “”，空字符串 ，这时候所有不带参数的页面 都会命中 这个空字符串作为的key的  同一缓存。

于是改成这样

```

Registry['APP_PAGE_CACHE_KEY'] = Registry['APP_NAME']..Registry['REQ_URI_PATH']..'?'..ngx.encode_args(clean_args(Registry['REQ_ARGS_ARR']))

```
 
说明：增加缓存匹配唯一APP_PAGE_CACHE_KEY = APP_NAME（项目名称） + ngx.var.uri(当前uri不带参数) + REQ_ARGS_ARR(参数)

这样每个页面的 缓存 APP_PAGE_CACHE_KEY 就不一样了。不管带不带参数。

**Comment by idevz** [comment]
@mind029 这里不用加啊，`APP_NAME` 在 Cache 里会自己加上啊。
你看看 `vanilla.v.cache.base` 中
```lua
local function _gen_cache_key(parent, key)
	return Registry['APP_NAME'] .. '_' .. str_sub(ngx.md5(key),1,10)
end
Base.cacheKey = _gen_cache_key
```
你这么改是你遇到什么问题了吗？

**Comment by mind029** [comment]
重点不是 APP_NAME  ，而是，当时访问的uri。ngx.var.uri ，加入到 key 里面才能作为唯一key。

单单使用 ngx.req.get_uri_args()  请求参数作为 key，如果都不穿， 得不到 唯一标识，

假设 APP_NAME =  web1

那么 cacheKey  =APP_NAME.. ngx.req.get_uri_args() 。不传参数时候 。
访问  www.xx.com/ 和 www.xx.com/list  key 都是   web1 .. '_' .. str_sub(ngx.md5(‘’),1,10) 
不同页面 都会从会这个 key 取同样内容，就污染了。

如果加入了 ngx.var.uri 那么 cacheKey  =APP_NAME..  ngx.var.uri  ..ngx.req.get_uri_args()  。

当访问 www.xx.com/ 的key为： web1 .. '_' .. str_sub(ngx.md5(‘’),1,10) 

当访问 www.xx.com/list 的key为： web1 .. '_' .. str_sub(ngx.md5(‘list’),1,10) 

这样就能得到不同页面不存key。第一次缓存不命中。第二次就会命中 当前url 组成的唯一key 设置的缓存了。

**Comment by idevz** [comment]
@mind029 你在仔细看看我的 KEY，
`Registry['APP_PAGE_CACHE_KEY'] = Registry['REQ_URI'] .. ngx.encode_args(clean_args(Registry['REQ_ARGS_ARR']))` 就是用的ngx_var.uri、APP_NAME和 Args。

**Comment by mind029** [comment]
已经接近 加入了 Registry['REQ_URI'] 能得到唯一key
